<template>
  <div class="multialpha-app">
    <TopBar :loading="listLoading" @home="navigateHome" @refresh="loadTraceIds" @create="openDialog('text')"/>
    <main class="app-main">
      <TaskSidebar :tasks="tasks" :active-id="currentTraceId" :loading="listLoading" :error="listError" @select="navigateTask" @retry="loadTraceIds"/>
      <LandingTerminal v-if="isHome" :tasks="tasks" @create="openDialog" @history="focusTasks"/>
      <section v-else-if="invalidTrace" class="invalid-trace"><span>404 · TRACE NOT FOUND</span><h2>未找到该任务</h2><p>{{ requestedTraceId }}</p><el-button type="primary" @click="navigateHome">返回终端首页</el-button></section>
      <template v-else>
        <section class="workspace"><DetailHeader :name="currentTask?.name||currentTraceId" :scenario="currentTask?.scenario||''" :status="currentTask?.status||'idle'" :loop="selectedLoop" @stop="stopCurrentTask"/><PipelineStages :messages="scopedMessages"/><TaskBrief :hypothesis="view.hypothesis" :config="view.config" :factors="view.initialTasks"/><AgentFlow :messages="scopedMessages" :factors="view.factors" :codes="view.codes" :metric-values="view.metricValues" :feedback="view.feedback" :hypothesis="view.hypothesis"/><LoopSwitcher v-model="selectedLoop" :loops="view.loops" :metrics="view.loopMetrics"/><TokenDashboard :total="view.totalTokens" :prompt="view.promptTokens" :completion="view.completionTokens" :calls="view.callCount"/><ResultWorkspace :factors="view.factors" :codes="view.codes" :chart-html="view.chartHtml" :metrics="view.metrics" :feedback="view.feedback" @download="downloadResult"/><TraceLoading :visible="loading" :name="loadingName"/></section>
        <MetricsPanel :metrics="view.metrics" :factors="view.factors" :hypothesis="view.hypothesis" :feedback="view.feedback" @download="downloadResult"/>
      </template>
    </main>
    <LogConsole :trace-id="currentTraceId" :status="currentTask?.status||'idle'"/><NewTaskDialog ref="dialogRef" v-model="dialogOpen" @submit="handleCreate"/><UserInteractionDialog :messages="messages" :trace-id="currentTraceId"/>
  </div>
</template>
<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ElMessage } from 'element-plus';import { useMultiAlpha } from './use-multialpha';import TopBar from './components/TopBar.vue';import TaskSidebar from './components/TaskSidebar.vue';import LandingTerminal from './components/LandingTerminal.vue';import DetailHeader from './components/DetailHeader.vue';import PipelineStages from './components/PipelineStages.vue';import TaskBrief from './components/TaskBrief.vue';import AgentFlow from './components/AgentFlow.vue';import LoopSwitcher from './components/LoopSwitcher.vue';import TokenDashboard from './components/TokenDashboard.vue';import ResultWorkspace from './components/ResultWorkspace.vue';import MetricsPanel from './components/MetricsPanel.vue';import LogConsole from './components/LogConsole.vue';import TraceLoading from './components/TraceLoading.vue';import NewTaskDialog from './components/NewTaskDialog.vue';import UserInteractionDialog from './components/UserInteractionDialog.vue';import type { TaskMethod } from './types'
const route=useRoute(),router=useRouter();const {tasks,currentTraceId,messages,loading,loadingName,listLoading,listError,selectedLoop,view,loadTraceIds,selectTrace,goHome,createTask,stopCurrentTask}=useMultiAlpha();const dialogOpen=ref(false);const dialogRef=ref<InstanceType<typeof NewTaskDialog>|null>(null)
const requestedTraceId=computed(()=>typeof route.params.traceId==='string'?route.params.traceId:'');const isHome=computed(()=>route.name==='multialpha-home');const currentTask=computed(()=>tasks.value.find(task=>task.id===currentTraceId.value));const invalidTrace=computed(()=>!isHome.value&&!listLoading.value&&!tasks.value.some(task=>task.id===requestedTraceId.value))
const scopedMessages=computed(()=>selectedLoop.value==null?messages.value:messages.value.filter(message=>message.loop_id==null||Number(message.loop_id)===selectedLoop.value))
async function syncRoute(){if(isHome.value){goHome();return}if(requestedTraceId.value&&!invalidTrace.value&&currentTraceId.value!==requestedTraceId.value)await selectTrace(requestedTraceId.value)}
watch(()=>route.fullPath,()=>void syncRoute());onMounted(async()=>{await loadTraceIds();await syncRoute()})
const navigateHome=()=>void router.push({name:'multialpha-home'});const navigateTask=(id:string)=>void router.push({name:'multialpha-task',params:{traceId:id}});function focusTasks(){document.querySelector('.task-sidebar')?.classList.add('attention');setTimeout(()=>document.querySelector('.task-sidebar')?.classList.remove('attention'),900)}function openDialog(method:TaskMethod){dialogOpen.value=true;requestAnimationFrame(()=>dialogRef.value?.open(method))}
async function handleCreate(payload:{method:TaskMethod;description:string;scenario:string;loops:number;files:File[]}){try{const id=await createTask(payload);dialogOpen.value=false;await router.push({name:'multialpha-task',params:{traceId:id}});ElMessage.success('任务已启动')}catch(error){ElMessage.error(error instanceof Error?error.message:'任务启动失败')}}
function downloadResult(){const data={traceId:currentTraceId.value,loop:selectedLoop.value,metrics:view.value.metricValues,factors:view.value.factors,codes:view.value.codes,feedback:view.value.feedback};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`multialpha_${currentTraceId.value.replace(/[\/\s]/g,'_')}.json`;link.click();URL.revokeObjectURL(url)}
</script>
